# Colors (Alabaster Dark)
# author tonsky

[colors.primary]
background = '#000000'
foreground = '#b5b5b5'

[colors.cursor]
text = '#0E1415'
cursor = '#b5b5b5'

[colors.normal]
black = '#000000'
red = '#b5b5b5'
green = '#b5b5b5'
yellow = '#b5b5b5'
blue = '#b5b5b5'
magenta = '#b5b5b5'
cyan = '#b5b5b5'
white = '#b5b5b5'

[colors.bright]
black = '#000000'
red = '#b5b5b5'
green = '#b5b5b5'
yellow = '#b5b5b5'
blue = '#b5b5b5'
magenta = '#b5b5b5'
cyan = '#b5b5b5'
white = '#b5b5b5'
