[general]
import = ["~/.config/alacritty/alabaster_dark.toml"]

[font]
normal = { family = "Iosevka Term", style = "Regular" }
bold = { family = "Iosevka Term", style = "Regular" }
size = 14

[cursor]
style = { shape = "Block" }
